name: Build and Test LLM-RAG

on:
  push:
    branches: [ "milestone4" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: |
          # Run flake8 on all .py files
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          echo "Flake8 linting completed" >> action_logs.txt

      - name: Conditional execution for automation branch or PRs to main
        if: github.ref == 'refs/heads/automation' || (github.event.pull_request && contains(github.head_ref, 'automation'))
        run: |
          cd src/llm-rag
          chmod +x ./test-shell.sh
          ./test-shell.sh
          echo "Executed automation script" >> action_logs.txt

      - name: Upload Logs as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
