name: CI

on:
  push:
    branches: [ "main", "automation" ]
  pull_request:
    branches: [ "main", "automation" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: List directories
        run: |
          pwd
          ls -la

      - name: Adjust path for automation branch
        if: contains(github.ref, 'refs/heads/automation')
        run: |
          cd src/llm-rag
          echo "Switched to automation branch directory"

      - name: Adjust path for main branch
        if: contains(github.ref, 'refs/heads/main')
        run: |
          echo "Main branch does not require directory change"

      - name: Change to script directory and run test shell script
        run: |
          cd src/llm-rag
          chmod +x ./test-shell.sh
          ./test-shell.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

