name: CI

on:
  push:
    branches: [ "main", "automation" ]
  pull_request:
    branches: [ "main", "automation" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          cd src/llm-rag
          docker build -t llm-rag-cli .

      - name: Run tests in Docker
        run: |
          cd src/llm-rag
          docker run -it --rm \
            -v "${{ github.workspace }}/src/llm-rag:/app" \
            --entrypoint /bin/bash \
            llm-rag-cli \
            -c "cd /app && PYTHONPATH=/app pipenv install --dev && PYTHONPATH=/app pipenv run pytest tests/ -v --cov=. --cov-report=term-missing"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
