name: CI

on:
  push:
    branches: [ "milestone4" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: List root directories after checkout
        run: |
          pwd
          ls -la

      - name: Conditional execution for automation branch or PRs to main
        if: github.ref == 'refs/heads/automation' || (github.event.pull_request && contains(github.head_ref, 'automation'))
        run: |
          cd src/llm-rag
          chmod +x ./test-shell.sh
          ./test-shell.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
